apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nezf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nezf
    app.kubernetes.io/part-of: byoc-app-jybo
  name: nezf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: nezf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: nezf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-ntao-tenant/byoc-app-jybo/nezf@sha256:aea3f4f17e6887445b4c80b0776311bce886dcc2bc12359269248151c54fcc74
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
